npm install --save jszip
npm install --save pdfmake
npm install --save datatables.net-bs4
npm install --save datatables.net-editor-bs4
npm install --save datatables.net-autofill-bs4
npm install --save datatables.net-buttons-bs4
npm install --save datatables.net-colreorder-bs4
npm install --save datatables.net-fixedcolumns-bs4
npm install --save datatables.net-fixedheader-bs4
npm install --save datatables.net-keytable-bs4
npm install --save datatables.net-responsive-bs4
npm install --save datatables.net-rowgroup-bs4
npm install --save datatables.net-rowreorder-bs4
npm install --save datatables.net-scroller-bs4
npm install --save datatables.net-select-bs4